### ISSUE TITLE
Resolved 3

### ISSUE THREAD

**Issue by GISScience** [FH-Potsdam/shifted-maps#55] opened 2019-11-21 11:49 UTC
Hi,
new to shifted map... Thanks for wonderful software.

**Comment by lennerd** [comment] 2019-11-21 21:45
Hey @GISScience, I‘m sorry but it is again very hard to help you in this very specific case. Again Shifted Maps was never built to be used as a standalone module or library. This does not meen it will not work as such but there might be a lot of work to be done to get it running correctly.

Please provide a reproducable repository or much more and more concret examples how you use Shifted Maps components, how you structured your application and how you provide data to it. Otherwise I really see no way to help you effectively.

**Comment by GISScience** [comment] 2019-11-22 02:23
Thank for reply , 
It may not be possible to provide reproducable repository immediately bcz of some unavoidable reasons....
 But just two point to clarify...
1. Is visualisation.tsx component is independent component and will it respond to change in its incoming data??
2. It seems, visualization.tsx is not changing except first time....
Is visualization store in shifted maps is designed to store value once and only update user interface ( making visibility on/off )based on time filter??
Thank in advance

**Comment by lennerd** [comment] 2019-11-22 09:40
Ah, I see.

The `Visualisation` component is indeed built in a way that it is initialising all the stores by using the incoming data only once on first render. You can see the corresponding code here: https://github.com/FH-Potsdam/shifted-maps/blob/c4c64c8734668c7007a95bd777562ddc5c35154c/components/Visualisation/Visualisation.tsx#L111

The `useFactory` hook is caching the result of the callback function, in this case the `DataStore` by never reinitializing the store. It’s a performance improvement because—like you said—Shifted Maps never needs to update the underlaying data set.

If you like you can provide a PR for extending the `useFactory` hook similar to the built-in React [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo) or [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback) hooks by providing a dependency array. I can try to look into this myself but I am currently moving to a new apartment and wont have time for this very soon.

**Comment by GISScience** [comment] 2019-11-22 17:02
Thanks for a quick response...
I didn't get what you means by 

> "extending the useFactory hook similar to the built-in React useMemo or useCallback hooks by providing a dependency array"

My problem is visStore object using useFactory is not correct...

1. I tried to replace useFactory with useMemo and useCallout but some or other error is coming...

2. I have remove useFactory from dataStore and it is working fine... then why with visStore , no CRS error is coming?

Sir, i am under strict deadlines , i will be thanks to you from internal core of my heart...

**Comment by lennerd** [comment] 2019-11-22 21:42
Removing the hook completly should work for your usecase just fine. Keep in mind though that you are recreate the stores on every render of the component which might lead to strange side effects or bad performance.

**Comment by GISScience** [comment] 2019-11-23 17:24
Sir @lennerd  thanks for quick reply...
 I have tried removing all hooks, but still it goes into infinite loop updating one store and then some other Stores automatically...

Due to lack of understanding of shifted-maps ,i am unable to solve this problem...

Please help me sir... I am under strict deadlines and from last 1 week, i am trying to do the same, but miserably failed multiple times...

Please spare some time for this issue sir...i will be lifelong thank full to you...

**Comment by lennerd** [comment] 2019-11-23 19:39
I‘m sorry, but I currently have no internet and won‘t have time until end of next week. If you can wait this long, I can try to implement a possible solution.

**Comment by GISScience** [comment] 2019-11-24 20:24
I donot have any other option , except to wait for your help...
I have tried all permutation and combination to render shifted map based on dynamic data...
please help me as soon as possible...
Thanks and Regards,
GISScience

**Comment by GISScience** [comment] 2019-11-29 17:27
Sir any update?? I have tried to put a dummy props to visualization and change it when data is changing, but still not charm on my face...
Any suggestions sir? Please help...

**Comment by GISScience** [comment] 2019-12-04 14:00
Sir, i am stuck.... Please help....

**Comment by lennerd** [comment] 2019-12-04 18:46
I pushed changes to the visualisation component on master. Because I do not have any other dataset to test this with I cannot gurantee it will work. But it should at least react to changes to the data property in some way.

**Comment by lennerd** [comment] 2019-12-17 07:13
Did you have time to test this?

**Comment by GISScience** [comment] 2019-12-17 07:34
Thanks for your help sir,

"no crs" exception is getting thrown using useRef hooks , it seems that some store is not getting map crs...

I have tried to preserve the crs rule in session store but didn't worked out...

**Comment by lennerd** [comment] 2019-12-17 08:07
No CRS with useRef? What do you mean with CRS? Where is the error thrown? You really need to be more specific. Otherwise I'm not able to help you and need to spend a lot of time only to understand your problem.

**Closed as completed** 2019-12-18 08:29 UTC
